name: onlineexamcontest
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0+1
#version: 3.0.0+3
#version: 7.0.0+7
#version: 7.0.0+9
#version: 3.0.0+3
#version: 7.0.0+9
#version: 8.0.0+10
#version: 9.0.0+11
#version: 10.0.0+12
version: 10.0.4+16


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  #carousel_slider: ^1.3.0
  flutter_swiper: 1.1.6
  percent_indicator: ^2.1.1
  flutter_speed_dial: ^1.2.1
  flutter_neumorphic: ^3.0.3
  form_field_validator: ^1.0.1
  font_awesome_flutter: ^8.7.0
  dio: ^3.0.10
  toast: ^0.1.5
  shared_preferences: ^0.5.12+4
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  flutter_webrtc: ^0.4.0
  http: ^0.12.2
  path_provider: ^1.6.24
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.1
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.10
  image_picker: ^0.6.6+5
  razorpay_flutter: ^1.2.5
  fluttertoast: ^7.1.8
  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  flutter_signin_button: ^1.1.0
  flutter_countdown_timer: ^1.2.0
  cashfree_pg: 2.0.2+21
  wc_form_validators: ^1.0.0
  badges: ^2.0.1
  in_app_update: ^2.0.0
  launch_review: ^3.0.1
  package_info: ^2.0.2
  #firebase_crashlytics: ^0.2.4
  #firebase_core: ^0.5.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.png
    - assets/images/profile.png
    - assets/images/key.png
    - assets/images/exam.png
    - assets/images/logout.png
    - assets/images/train.png
    - assets/images/wallet.png
    - assets/images/deposit.png
    - assets/images/withdraw.png
    - assets/images/info.png
    - assets/images/arrow.png
    - assets/images/medal1.png
    - assets/images/msg.png
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/images/tran.png
    - assets/images/uparrow.png
    - assets/images/camera_profile.png
    - assets/images/check.png
    - assets/images/sucess.png
    - assets/images/circle.png
    - assets/images/sucesscontest.png
    - assets/images/img1.JPEG
    - assets/images/phonpay.png
    - assets/images/gpy.png
    - assets/images/bank.png
    - assets/images/startscreen.JPEG
    - assets/images/books.png
    - assets/images/logonew.png
    - assets/images/logoanimate.GIF
    - assets/images/loginlogo.png
    - assets/images/wincup.jpg
    - assets/images/search1.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
